version: 2

models:
  - name: stg_tpch_customers
    description: Cleaned customer data from TPCH source
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_tpch_orders
    description: Cleaned orders data
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null

  - name: stg_tpch_lineitems
    description: Order line level data
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null